name: Caller Workflow

on: workflow_dispatch

jobs:
  calling-workflow:
    uses: SnykHeidemann/java-goof/.github/workflows/snyk-gha-cli-template.yml@main  # Specify repo and branch
    with:
      flag_test: "--all-projects"
      flag_code: "--severity-threshold=high"
      flag_iac: "--severity-threshold=medium"
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
