name: Caller Workflow

on: workflow_dispatch

jobs:
  calling-workflow:
    uses: SnykHeidemann/Snyk-cicd-templates/.github/workflows/snyk-gha-cli-template.yml@main  # Specify repo and branch
    with:
      flag.test: "--all-projects"
      flag.code: "--report"
      flag.iac: "--report"
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
